title: Tensor Toolbox
description: Tensor Toolbox for Modern Fortran
theme: just-the-docs

url: https://adtzlr.github.io/ttb
logo: "assets/images/logo.svg"

math: mathjax

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple

aux_links:
  Tensor Toolbox on GitHub: https://github.com/adtzlr/ttb